# Generated by Django 3.1.1 on 2021-06-21 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='customer_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Customer'), (2, 'Distributor')], null=True),
        ),
        migrations.CreateModel(
            name='BlendingOptionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blending_option_1', models.CharField(blank=True, max_length=100, null=True)),
                ('blending_option_2', models.CharField(blank=True, max_length=100, null=True)),
                ('blending_option_3', models.CharField(blank=True, max_length=100, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_api.customermodel')),
            ],
            options={
                'verbose_name': 'Blending Options Model',
            },
        ),
    ]
