# Generated by Django 3.1.1 on 2021-06-21 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsandconditionsmodel',
            name='shop',
        ),
        migrations.DeleteModel(
            name='BankdetailModel',
        ),
        migrations.DeleteModel(
            name='TermsandConditionsModel',
        ),
    ]
