# Generated by Django 3.1.1 on 2021-06-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_auto_20210621_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='product_mrp_price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='product_expiry',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='product_template',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='product_value',
        ),
    ]
