# Generated by Django 3.1.1 on 2021-06-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_auto_20210621_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_mrp_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
