# Generated by Django 3.1.1 on 2021-06-25 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_auto_20210621_2053'),
        ('core_api', '0005_auto_20210625_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_api.customermodel'),
        ),
    ]
