# Generated by Django 3.1.1 on 2021-06-25 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0006_ordermodel_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupounmodel',
            name='coupoun_remaining_limit',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
