# Generated by Django 3.1.1 on 2021-06-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0007_coupounmodel_coupoun_remaining_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='coupoun_applied',
            field=models.BooleanField(default=False),
        ),
    ]
